Try to match `$spack_release` for other repos where appropriate
Handle repos distinguishing between Spack's and their own version numbers

diff --git a/bin/make_spack b/bin/make_spack
--- a/bin/make_spack
+++ b/bin/make_spack
@@ -12,10 +12,18 @@ find_ourselves() {
 }
 
 clone_repos() {
-    while read ddir branch repo
+    if [ "$spack_release" != "fnal-develop" ]; then
+      # Trigger attempt to use a branch corresponding to the
+      # $spack_release branch requested for Spack.
+      maybe_change_branch=1
+    else
+      unset maybe_change_branch
+    fi
+    while read ddir branch repo branch_prefix branch_suffix
     do
       if [ "$repo" = "$spack_repo" ] ; then
         repo_type=spack
+        unset maybe_change_branch
       elif [[ "${ddir#$dir/}" == etc/* ]]; then
         repo_type=etc
       elif [[ "${ddir#$dir/var/spack/}" == extensions/* ]]; then
@@ -29,6 +37,19 @@ clone_repos() {
       else
         unset repo_type
       fi
+      if [ -n "$maybe_change_branch" ]; then
+        default_branch="$branch"
+        branch="${spack_release%-fermi}"
+        if [[ "$branch" == v[0-9]* ]]; then
+          branch="$branch_prefix$branch$branch_suffix"
+        fi
+        if [ "$branch" = "$default_branch" ]; then
+          unset $default_branch
+        fi
+      else
+        unset default_branch
+      fi
+      clone_branch=${default_branch:-$branch}
       if [ -e "$ddir/.git" ]; then
         if [ -n "$repo_type" ]; then
           eval "upgrade_repo=\$upgrade_$repo_type"
@@ -58,18 +79,23 @@ clone_repos() {
         fi
       else
         if $verbose; then
-          echo "$(date --iso-8601=seconds) Cloning Git repository on branch $branch at"
+          echo "$(date --iso-8601=seconds) Cloning Git repository on branch $clone_branch at"
           echo "$(date --iso-8601=seconds)   $ddir"
         fi
-        if ! git clone -b $branch --depth $depth $repo $ddir; then
-          echo "$(date --iso-8601=seconds) Unable to clone Git repository on branch $branch at" 1>&2
+        if ! git clone -b $clone_branch --depth $depth $repo $ddir; then
+          echo "$(date --iso-8601=seconds) Unable to clone Git repository on branch $clone_branch at" 1>&2
           echo "$(date --iso-8601=seconds)   $ddir" 1>&2
           echo "$(date --iso-8601=seconds) Fix manually" 1>&2
+          [ -z "$default_branch" ] || {
+            git -C $ddir switch $branch >/dev/null 2>&1 &&
+              $verbose &&
+              echo "$(date --iso-8601=seconds) switched from $clone_branch to $branch based on selection of Spack branch $spack_release"
+          }
         fi
       fi
     done <<EOF
         $dir                                            $spack_release  $spack_repo
-        $dir/etc/spack/linux                            main            https://github.com/FNALssi/fermi-etc-spack-linux.git
+        $dir/etc/spack/linux                            main            https://github.com/FNALssi/fermi-etc-spack-linux.git      spack-
         $dir/var/spack/extensions/spack-freeze          main            https://github.com/FNALssi/spack-freeze.git
         $dir/var/spack/extensions/spack-installdir      main            https://github.com/FNALssi/spack-installdir.git
         $dir/var/spack/extensions/spack-intersection    main            https://github.com/FNALssi/spack-intersection.git
