use log with summary messages approach for make_subspack, too (#13)

diff --git a/bin/make_subspack b/bin/make_subspack
--- a/bin/make_subspack
+++ b/bin/make_subspack
@@ -17,8 +17,9 @@ parse_args() {
     spack_repo=$(get_from_bootstrap default_spack_repo)
     spack_release=$(get_from_bootstrap  default_spack_version)
     padding=false
+    verbose=false
 
-    eval set : $(getopt --longoptions with_padding,spack_release:,spack_repo --options tu -- "$@")
+    eval set : $(getopt --longoptions with_padding,spack_release:,spack_repo --options vtu -- "$@")
     shift
 
     while echo x$1 | grep x- > /dev/null
@@ -29,6 +30,7 @@ parse_args() {
         x--spack_repo)    spack_repo=$2; shift; shift;;
         x-t) unified=false; shift ;;
         x-u) unified=true; shift ;;
+        x-u) verbose=true; shift ;;
         x--) shift; break;;
         esac
     done
@@ -36,19 +38,70 @@ parse_args() {
 
     if [ $# != 2 ]
     then
-        echo "usage: make_subspack [-t|-u] /path/to/existing/spack /path/to/new/area"
+        echo "usage: make_subspack [options] [-t|-u] path/to/existing/spack /path/to/new/area"
+        echo " options are:"
+        echo "--with_padding      enable directory padding in config"
+        echo "--spack_release xx  install spack release xx"
+        echo "--spack_repo url    use spack repo url"
+        echo "-v                  verbose"
+        echo "-t                  traditional layout"
+        echo "-u                  unified layout (default)"
+         
         exit 1
     fi
 
     src=$1
     dst=$2
 
-    echo "spack_release is $spack_release"
-
     case "$spack_release" in
     rollout*) extra="";;
     *)        extra=".new";;
     esac
+}
+
+
+detail_log() {
+    logfile=/tmp/make_subspack_$$.log 
+    # use fd 3 for messages to user, send stdout and stderr to log
+    # redirect stdin from /dev/null, so anything that tries to prompt
+    # for input will fail and not hang because no message gets to the user
+    exec 3>&1 > $logfile 2>&1 < /dev/null
+    echo "Putting detail log in $logfile" >&3 
+}
+
+monitor() {
+   local f=$1
+   local sd=$2
+   local box="[                                                  ]"
+   local lin="[==================================================]"
+
+   printf "%3d%%$box\r" 0 >&3
+   while :
+   do
+       local duf=$(du -b $f)
+       local ds="${duf%$f}"
+       dpp1=$(( ds / sd ))
+       (( dpp1 > 99 )) && dpp1=99
+       dpp2=$(( dpp1 / 2 + 1 ))
+       printf "%3d%%${lin:0:$dpp2}\r" $dpp1 >&3
+       sleep 2
+   done
+}
+start_monitor() {
+  monitor $* &
+  monitor_pid=$!
+  trap "stop_monitor" EXIT
+}
+stop_monitor() {
+  (( monitor_pid )) && kill $monitor_pid
+  wait
+  clr="                                                         "
+  printf "\r$clr\r" >&3
+}
+message() {
+    stop_monitor
+    echo $* >&3
+    start_monitor $logfile 719
 }
 
 
@@ -59,6 +112,17 @@ x*)  spackbindir="$PWD/$spackbindir"
 esac
 
 parse_args "$@"
+
+if $verbose
+then
+    message() {
+       echo $*
+    }
+    message Running in verbose mode:
+else
+    detail_log
+    set -x
+fi
 
 # assume unified layout...
 if $unified
@@ -76,7 +140,7 @@ install_tcl_path=$src/share/spack/modules
 
 if [ -d "$install_tree_path/__spack_path_placeholder__" ]
 then
-    echo "Checking for padded .spack-db"
+    message "Checking for padded .spack-db"
     install_tree_path=$(find $install_tree_path/__spack_path_placeholder__ -name .spack-db -print | head -1 | sed -e 's;/.spack-db;;')
 fi
 
@@ -90,6 +154,8 @@ mkdir -p $SPACK_ROOTd
 export SPACK_ROOT
 
 test -d $SPACK_ROOTd || mkdir -p $SPACK_ROOTd
+
+message git clone-ing spack
 
 cd $SPACK_ROOTd
 case "$spack_root" in
@@ -107,16 +173,16 @@ else
 cp $spackbindir/../templates/config.yaml.traditional${extra} $SPACK_ROOT/etc/spack/config.yaml
 fi
 
-echo "installing packages.yaml"
+message "installing packages.yaml"
 cp $src/etc/spack/packages.yaml $SPACK_ROOT/etc/spack/packages.yaml
 
 if $padding 
 then 
-    echo "turning on padding." 
+    message "turning on padding." 
     echo "    padded_length: 255" >> $SPACK_ROOT/etc/spack/config.yaml
 fi
 
-echo "installing upstreams.yaml..."
+message "installing upstreams.yaml..."
 cat >> etc/spack/upstreams.yaml <<EOF
 
  upstreams:
@@ -125,6 +191,8 @@ cat >> etc/spack/upstreams.yaml <<EOF
       modules:
         tcl: $install_tcl_path
 EOF
+
+message "building setup-env scripts"
 
 echo  > $dst/setup-env.sh
 echo "export SPACK_SKIP_MODULES=true" >> $dst/setup-env.sh
@@ -135,6 +203,8 @@ echo  > $dst/setup-env.csh
 echo "setenv SPACK_SKIP_MODULES true" >> $dst/setup-env.csh
 echo "setenv SPACK_DISABLE_LOCAL_CONFIG true" >> $dst/setup-env.csh
 echo "source $SPACK_ROOT/share/spack/setup-env.csh" >> $dst/setup-env.csh
+
+message "using upstream's bootstrap" 
 
 mkdir -p $dst/tmp
 # reuse upstream clingo bootstrap
@@ -150,7 +220,7 @@ mkdir $SPACK_ROOT/etc/spack/$os
 
 # now clone package repos..
 
-echo "adding package repos..."
+message "adding package repos..."
 
 ( SPACK_ROOT=$src $src/bin/spack repo list ) | (
     
@@ -165,10 +235,10 @@ echo "adding package repos..."
     done
 )
 
-echo "Adding buildcache $binary_cache"
+message "Adding buildcache $binary_cache"
 $SPACK_ROOT/bin/spack mirror add --scope site fnal $binary_cache
 $SPACK_ROOT/bin/spack buildcache update-index  -d $binary_cache
-echo "Adding backup buildcache $binary_cache_bak"
+message "Adding backup buildcache $binary_cache_bak"
 $SPACK_ROOT/bin/spack mirror add --scope site scisoft $binary_cache_bak
 $SPACK_ROOT/bin/spack buildcache update-index  -d $binary_cache_bak
 $SPACK_ROOT/bin/spack -k buildcache keys --install --trust --force
