Support `--upgrade-{etc,extensions,spack}` for existing installations

diff --git a/bin/make_spack b/bin/make_spack
--- a/bin/make_spack
+++ b/bin/make_spack
@@ -14,7 +14,55 @@ find_ourselves() {
 clone_repos() {
     while read ddir branch repo
     do
-        git clone -b $branch --depth $depth $repo $ddir
+      if [ -e "$ddir/.git" ]; then
+        if [ "$repo" = "$spack_repo" ] ; then
+          repo_type=spack
+        elif [[ "${ddir#$dir/}" == etc/* ]]; then
+          repo_type=etc
+        elif [[ "${ddir#$dir/var/spack/}" == extensions/* ]]; then
+          repo_type=extensions
+        else
+          unset repo_type
+        fi
+        if [ -n "$repo_type" ]; then
+          eval "upgrade_repo=\$upgrade_$repo_type"
+        else
+          unset upgrade_repo
+        fi
+        current_branch=$(git -C "$ddir" branch --show-current)
+        if (( upgrade_repo )); then
+          if [ "$current_branch" = "$branch" ]; then
+            if $verbose; then
+              echo "$(date --iso-8601=seconds) Updating Git repository at $ddir"
+            fi
+            if ! git -C "$ddir" pull; then
+              echo "$(date --iso-8601=seconds) Unable to update Git repository at" 1>&2
+              echo "$(date --iso-8601=seconds)   $ddir" 1>&2
+              echo "$(date --iso-8601=seconds) Fix manually" 1>&2
+            fi
+          else
+            echo "$(date --iso-8601=seconds) Refusing to update Git repository from branch $current_branch to $branch at" 1>&2
+            echo "$(date --iso-8601=seconds)   $ddir" 1>&2
+            echo "$(date --iso-8601=seconds) Fix manually" 1>&2
+            exit 2
+          fi
+        else
+          echo "$(date --iso-8601=seconds) Using existing repository on branch $current_branch at "
+          echo "$(date --iso-8601=seconds)   $ddir"
+          echo "$(date --iso-8601=seconds) Use --upgrade-$repo_type or upgrade manually"
+        fi
+      else
+        if $verbose; then
+          echo "$(date --iso-8601=seconds) Cloning Git repository on branch $branch at"
+          echo "$(date --iso-8601=seconds)   $ddir"
+        fi
+        if ! git clone -b $branch --depth $depth $repo $ddir; then
+          echo "$(date --iso-8601=seconds) Unable to clone Git repository on branch $branch at" 1>&2
+          echo "$(date --iso-8601=seconds)   $ddir" 1>&2
+          echo "$(date --iso-8601=seconds) Fix manually" 1>&2
+          exit 2
+        fi
+      fi
     done <<EOF
         $dir                                            $spack_release  $spack_repo
         $dir/etc/spack/linux                            main            https://github.com/marcmengel/fermi-etc-spack-linux.git
@@ -76,7 +124,10 @@ query_packages() {
 usage() {
         echo "Usage: $0 [options] -[utp] /base/directory"
         echo " options:"
-        echo "  --upgrade"
+        echo "  --upgrade (deprecated, ignored)"
+        echo "  --upgrade-etc"
+        echo "  --upgrade-extensions"
+        echo "  --upgrade-spack"
         echo "  --no-buildcache"
         echo "  --query-packages"
         echo "  --spack_release ver"
@@ -114,7 +165,7 @@ parse_args() {
     depth=1
 
     origargs="$*"
-    if x=$(getopt --longoptions help,depth,with_padding,upgrade,spack_release:,minimal,no_buildcache,repover,spack_repo:,query-packages,verbose --options mptuv -- "$@")
+    if x=$(getopt --longoptions help,depth,with_padding,upgrade,upgrade-etc,upgrade-extensions,upgrade-spack,spack_release:,minimal,no_buildcache,repover,spack_repo:,query-packages,verbose --options mptuv -- "$@")
     then
         eval set : $x
         shift
@@ -127,7 +178,8 @@ parse_args() {
         case "x$1" in
         x--depth)               depth=$2; shift;;
         x--with_padding)        padding=true; shift ;;
-        x--upgrade)             echo "Deprecated option --upgrade ignored";  shift;;
+        x--upgrade)             echo "Deprecated option --upgrade ignored: use --upgrade-{etc,extensions,spack} ";  shift;;
+        x--upgrade-*)           upgrade_${1##*-}=1; shift;;
         x--spack_release)       spack_release=$2; shift; shift ;;
         x--spack_repo)          spack_repo=$2; shift; shift;;
         x--minimal)             minimal=true; shift ;;
